#include "totvs.ch"

procedure u_PeVirg01() 

    local cVar  as character
    cVar:="ESTA VAI SER UMA ATRIBUIÇÃO DE VARIAS LINHAS PQ EU SOU PREGUICOSO";
+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO" ;
+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO" ;
+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO" 

    cVar:="ESTA VAI SER UMA ATRIBUIÇÃO DE VARIAS LINHAS PQ EU SOU PREGUICOSO"
    cVar:=cVar+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"
    cVar:=cVar+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"
    cVar:=cVar+"E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"

    cVar:="ESTA VAI SER UMA ATRIBUIÇÃO DE VARIAS LINHAS PQ EU SOU PREGUICOSO"
    cVar+="E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"
    cVar+="E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"
    cVar+="E QUERO FAZER DESTE JEITO E QUERO FAZER DESTE JEITO"

    return
